apiVersion: v1
kind: Service
metadata:
    name: john
    namespace: data-analytics
spec:
  ports:
  - port: 80
    name: jupyter-john
    protocol: TCP
    targetPort: 8888
  type: LoadBalancer
  selector:
    app: jupyter-john
---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: jupyter-john
  namespace: data-analytics
  labels:
    app: jupyter-john
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jupyter-john
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: jupyter-john
        lab: jupyter
    spec:
      volumes:
      - name: data
        persistentVolumeClaim:
          claimName: clone-datalake-john
      containers:
      - name: notebook
        image: jupyter/datascience-notebook:latest
        ports:
        - containerPort: 8888
          protocol: TCP
        command: ["start-notebook.sh"]
        args: ["--NotebookApp.token=''"]          
        resources:
          limits:
            memory: 512Mi
        volumeMounts:
        - name: data
          mountPath: "/home/jovyan"
        env:
        - name: JUPYTER_ENABLE_LAB
          value: 'yes'
      automountServiceAccountToken: false
