apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: nas-gold
provisioner: csi.trident.netapp.io
parameters:
  backendType: "ontap-nas"
  media: "ssd"
  provisioningType: "thick"
  encryption: "true"
reclaimPolicy: Retain
allowVolumeExpansion: true
